export default {
    data() {
        return {
            portfolios: [
                {
                    id: 1,
                    img: require(`@/assets/images/portfolio/PredictPushback.jpg`),
                    title: "Pushback to the Future: Predict Pushback Time at US Airports",
                    framework: "Lightgbm, Tensorflow, Pytorch, Scikit-learn, Pandas",
                    contributors: "Me, Kyler Robison, Trevor Tomlin, Daniil Filienko",
                    language: "Python",
                    preview: "drivendata.co",
                    previewLink: "https://drivendata.co/blog/airport-pushback-finalists",
                },
                {
                    id: 2,
                    img: require(`@/assets/images/portfolio/YourProfile.webp`),
                    title: "Your Profile",
                    framework: "Tensorflow",
                    contributors: "Me, Anthony Nguyen, Brian LeSmith",
                    language: "Python",
                    preview: "github.com",
                    previewLink: "https://github.com/HuskyDevClub/YourProfile",
                },
                {
                    id: 3,
                    img: require(`@/assets/images/portfolio/linpg.png`),
                    title: "Linpg Engine",
                    framework: "Pygame-ce, Numpy",
                    contributors: "Me",
                    language: "Python",
                    preview: "github.com",
                    previewLink: "https://github.com/LinpgFoundation/linpg",
                },
                {
                    id: 4,
                    img: require(`@/assets/images/portfolio/GFL-LastWish.png`),
                    title: " GFL - Last Wish",
                    framework: "Linpg Engine 3",
                    contributors: "Me",
                    language: "Python",
                    preview: "github.com",
                    previewLink: "https://github.com/TigeiaWorkshop/GFL-LastWish",
                },
                {
                    id: 5,
                    img: require(`@/assets/images/portfolio/linpgtoolbox.jpg`),
                    title: "Linpg Toolbox",
                    framework: "Cython, Pyinstaller, Twine",
                    contributors: "Me",
                    language: "Python",
                    preview: "github.com",
                    previewLink: "https://github.com/LinpgFoundation/linpg-toolbox",
                },
                {
                    id: 6,
                    img: require(`@/assets/images/portfolio/A-story-of-us.png`),
                    title: " A Story of Us",
                    framework: "Linpg Engine 3",
                    contributors: "Me",
                    language: "Python",
                    preview: "github.com",
                    previewLink:
                        "https://github.com/LinpgFoundation/A-story-of-us",
                },
                {
                    id: 7,
                    img: require(`@/assets/images/portfolio/SundewValley.png`),
                    title: "Sundew Valley",
                    framework: "Web Application",
                    contributors: "Me, Andrew Lau Ho YIn, Brian LeSmith, Kevin Yang",
                    language: "JavaScript",
                    preview: "huskydevclub.github.io",
                    previewLink: "https://huskydevclub.github.io/SundewValley/",
                },
                {
                    id: 8,
                    img: require(`@/assets/images/portfolio/DungeonAdventure.gif`),
                    title: "Dungeon Adventure",
                    framework: "Jungeon Engine",
                    contributors: "Me, Griffin Ryan, and Elijah Amian",
                    language: "Java",
                    preview: "github.com",
                    previewLink:
                        "https://github.com/HuskyDevClub/DungeonAdventure",
                },
                {
                    id: 9,
                    img: require(`@/assets/images/portfolio/petblocks.jpg`),
                    title: "Pet Blocks",
                    framework: "Sponge",
                    contributors: "Christoph, Yannick Schinko, and Me, and so on",
                    language: "Java",
                    preview: "github.com",
                    previewLink:
                        "https://github.com/Shynixn/PetBlocks",
                },
            ],
        };
    },
};
